"""Public library surface for the real estate parser."""

from real_estate_parser.application import (
    LocalSearchFailure,
    LocalSearchResult,
    LocalSearchSuccess,
    run_local_search,
)
from real_estate_parser.collection import (
    CollectionBuildFailure,
    CollectionBuildResult,
    CollectionBuildSuccess,
    CollectionSnapshot,
    build_fixture_collection,
)
from real_estate_parser.fixture_source_adapter import adapt_fixture_source_batch
from real_estate_parser.fixture_source_batch import load_fixture_source_batch
from real_estate_parser.normalization import (
    FIXTURE_NORMALIZATION_RULES_V1,
    Area,
    Currency,
    FieldOutcome,
    FixtureNormalizationRules,
    LocationText,
    Missing,
    MissingProvenance,
    MoneyAmount,
    NormalizationFailure,
    NormalizationResult,
    NormalizationRuleVersion,
    NormalizationSuccess,
    NormalizedListing,
    ObservedAt,
    Present,
    RoomCount,
    SourceUrl,
    TracedValue,
    Unsupported,
    UnsupportedProvenance,
    ValueProvenance,
    normalize_fixture_snapshot,
)
from real_estate_parser.search import SearchMatch, SearchResult, search_collection
from real_estate_parser.search_criteria import (
    Money,
    SearchCriteria,
    SearchCriteriaLoadFailure,
    SearchCriteriaLoadResult,
    SearchCriteriaLoadSuccess,
)
from real_estate_parser.search_criteria_boundary import load_search_criteria
from real_estate_parser.search_result_boundary import (
    SearchResultSerializationFailure,
    SearchResultSerializationResult,
    SearchResultSerializationSuccess,
    serialize_search_result_document,
)
from real_estate_parser.search_result_mapping import (
    FieldOutcomeDocument,
    MissingDocument,
    MissingProvenanceDocument,
    MoneyDocument,
    PresentDocument,
    ProvidedProvenanceDocument,
    PublicationRefDocument,
    SearchCriteriaDocument,
    SearchMatchDocument,
    SearchResultDocument,
    TracedValueDocument,
    UnsupportedDocument,
    map_search_result,
)
from real_estate_parser.source_batch import (
    ContractIssue,
    FixtureSourceAdaptationFailure,
    FixtureSourceAdaptationResult,
    FixtureSourceAdaptationSuccess,
    InputLocation,
    MissingField,
    MissingSourceField,
    PublicationId,
    PublicationRef,
    RawField,
    SourceBatch,
    SourceBatchLoadFailure,
    SourceBatchLoadResult,
    SourceBatchLoadSuccess,
    SourceId,
    SourcePublicationSnapshot,
    ValidatedSourceBatch,
    ValidatedSourceField,
    ValidatedSourceListing,
)

__version__ = "0.1.0"

__all__ = [
    "Area",
    "CollectionBuildFailure",
    "CollectionBuildResult",
    "CollectionBuildSuccess",
    "CollectionSnapshot",
    "ContractIssue",
    "Currency",
    "FIXTURE_NORMALIZATION_RULES_V1",
    "FieldOutcome",
    "FieldOutcomeDocument",
    "FixtureSourceAdaptationFailure",
    "FixtureSourceAdaptationResult",
    "FixtureSourceAdaptationSuccess",
    "FixtureNormalizationRules",
    "InputLocation",
    "LocationText",
    "LocalSearchFailure",
    "LocalSearchResult",
    "LocalSearchSuccess",
    "Missing",
    "MissingDocument",
    "MissingField",
    "MissingProvenance",
    "MissingProvenanceDocument",
    "MissingSourceField",
    "Money",
    "MoneyDocument",
    "MoneyAmount",
    "NormalizationFailure",
    "NormalizationResult",
    "NormalizationRuleVersion",
    "NormalizationSuccess",
    "NormalizedListing",
    "ObservedAt",
    "Present",
    "PresentDocument",
    "ProvidedProvenanceDocument",
    "PublicationId",
    "PublicationRef",
    "PublicationRefDocument",
    "RawField",
    "RoomCount",
    "SearchCriteria",
    "SearchCriteriaDocument",
    "SearchCriteriaLoadFailure",
    "SearchCriteriaLoadResult",
    "SearchCriteriaLoadSuccess",
    "SearchMatch",
    "SearchMatchDocument",
    "SearchResult",
    "SearchResultDocument",
    "SearchResultSerializationFailure",
    "SearchResultSerializationResult",
    "SearchResultSerializationSuccess",
    "SourceBatch",
    "SourceBatchLoadFailure",
    "SourceBatchLoadResult",
    "SourceBatchLoadSuccess",
    "SourceId",
    "SourcePublicationSnapshot",
    "SourceUrl",
    "TracedValue",
    "TracedValueDocument",
    "Unsupported",
    "UnsupportedDocument",
    "UnsupportedProvenance",
    "ValidatedSourceBatch",
    "ValidatedSourceField",
    "ValidatedSourceListing",
    "ValueProvenance",
    "__version__",
    "adapt_fixture_source_batch",
    "build_fixture_collection",
    "load_fixture_source_batch",
    "load_search_criteria",
    "map_search_result",
    "normalize_fixture_snapshot",
    "run_local_search",
    "search_collection",
    "serialize_search_result_document",
]
